# Generated by Django 4.2.14 on 2024-07-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model_prac", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyModel",
            fields=[
                (
                    "customer_id",
                    models.CharField(
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Customer Id",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
