# Generated by Django 4.2.14 on 2024-07-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model_prac", "0002_mymodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyModel1",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
